language: node_js
node_js:
  - "8.11"
install:
  - npm install
cache:
  directories:
  - node_modules
script:
  - npm run build
notifications:
  email:
    on_pull_requests: false
    on_success: never
    on_failure: never
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_AUTH_TOKEN
  local_dir: build
  verbose: true
  on:
    branch: master
